name: flutterdistractionappnew
description: A Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/alarm.mp3
    - assets/studyBackground.jpg

# (Optional) If the Linux plugin causes warnings, you can override it:
dependency_overrides:
  flutter_local_notifications_linux: ^6.0.0
